name: Execution and Link Testing (Nightly)
on:
  schedule:
    - cron: '0 17 * * *'
jobs:
  coverage:
    name: Run Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Anaconda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          auto-activate-base: true
          miniconda-version: 'latest'
          python-version: 3.7
          environment-file: environment.yml
          activate-environment: qe-lectures
      - name: Run Execution Tests
        shell: bash -l {0}
        run: make coverage
  linkchecker:
    name: Run linkchecker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Anaconda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          auto-activate-base: true
          miniconda-version: 'latest'
          python-version: 3.7
          environment-file: environment.yml
          activate-environment: qe-lectures
      - name: Run Linkchecker
        shell: bash -l {0}
        run: make linkcheck
  build-cache:
    name: Build Cache of Website (Nightly)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Anaconda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          auto-activate-base: true
          miniconda-version: 'latest'
          python-version: 3.7
          environment-file: environment.yml
          activate-environment: qe-lectures
      - name: Checkout QuantEcon theme
        uses: actions/checkout@v2
        with:
          repository: QuantEcon/lecture-python-advanced.theme
          token: ${{ secrets.ACTIONS_PAT }}
          path: theme/lecture-python-advanced.theme
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Cache Website Build Folder
        id: cache
        uses: actions/cache@v1
        with:
          path: _build
          key: cache-sphinx-${{ steps.date.outputs.date }}
      - name: Build Website files
        shell: bash -l {0}
        run: |
          make website THEMEPATH=theme/lecture-python-advanced.theme
          ls _build/website/jupyter_html/*